#!/bin/sh
if test -z "$(command -v time)"; then
    echo executable "time" is not installed.
    exit 1
fi
arch="${1}"
shift
echo sudo sbuild-update -udcar unstable-${arch}-sbuild --chroot-mode=schroot
sudo sbuild-update -udcar unstable-${arch}-sbuild --chroot-mode=schroot
echo time sbuild --no-clean -c unstable-${arch}-sbuild --build=${arch} --arch=${arch} $@
time sbuild --no-clean -c unstable-${arch}-sbuild --build=${arch} --arch=${arch} $@
