#!/bin/sh
# ref: https://wiki.debian.org/sbuild#Enabling_experimental

# parse args
arch="${1}"
mirror="http://t490"
shift

# scan remaining args for --exp/--experimental, extracting it out of $@
exp=""
args=""
for a in "$@"; do
    case "${a}" in
        --exp|--experimental)
            exp="1"
            ;;
        *)
            args="${args} ${a}"
            ;;
    esac
done
set -- ${args}

# check eatmydata
if test -e /usr/lib/x86_64-linux-gnu/libeatmydata.so; then
    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libeatmydata.so
elif test -e /usr/lib/aarch64-linux-gnu/libeatmydata.so; then
    export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libeatmydata.so
fi

if test -n "${exp}"; then
    # do sbuild with experimental (buildd) enabled
    echo sbuild --no-clean -c unstable-${arch} --build=${arch} --arch=${arch} \
        --extra-repository="deb ${mirror} experimental main contrib non-free" \
        --aspcud-criteria '-count(down),-count(changed,APT-Release:=/experimental/),-removed,-changed,-new' \
        --build-dep-resolver=aspcud $@
    sbuild --no-clean -c unstable-${arch} --build=${arch} --arch=${arch} \
        --extra-repository="deb ${mirror} experimental main contrib non-free" \
        --aspcud-criteria '-count(down),-count(changed,APT-Release:=/experimental/),-removed,-changed,-new' \
        --build-dep-resolver=aspcud $@
else
    # do standard sbuild
    echo sbuild --no-clean -c unstable-${arch} --build=${arch} --arch=${arch} $@
    sbuild --no-clean -c unstable-${arch} --build=${arch} --arch=${arch} $@
fi
