#!/bin/sh
arch=${1}
shift
echo sudo sbuild-update -udcar unstable-${arch}-sbuild
sudo sbuild-update -udcar unstable-${arch}-sbuild
echo time sbuild --no-clean -c unstable-${arch}-sbuild --build=${arch} --arch=${arch} $@
time sbuild --no-clean -c unstable-${arch}-sbuild --build=${arch} --arch=${arch} $@
