#!/bin/sh
# Write/remove a task to do later.
# Copied from http://tools.suckless.org/dmenu/scripts/todo
# Slightly Modified.
SB="#7b1d8c"
SF="#cccccc"
NB="#cccccc"
NF="#7b1d8c"
FN="Inconsolata:size=13"
#DMENU="dmenu -b"  # bottom
DMENU="dmenu"  # top
#DMENU="rofi -dmenu"

FILE=~/.todo
HEIGHT=$(cat $FILE | wc -l)
PROMPT="TODO ❯"

ACTION="cat $FILE | $DMENU -fn $FN -l '$HEIGHT' -nb '$NB' -nf '$NF' -sb '$SB' -sf '$SF' -p '$PROMPT' "
CMD=$(eval $ACTION)
while [ -n "$CMD" ]; do
	grep -q "^$CMD" $FILE
	if [ $? = 0 ]; then
		grep -v "^$CMD" $FILE > /tmp/todo
		mv /tmp/todo $FILE
        HEIGHT=$(($HEIGHT-1))
        ACTION="cat $FILE | $DMENU -fn $FN -l '$HEIGHT' -nb '$NB' -nf '$NF' -sb '$SB' -sf '$SF' -p '$PROMPT' "
	else
		echo "$CMD" >> $FILE
        HEIGHT=$(($HEIGHT+1))
        ACTION="cat $FILE | $DMENU -fn $FN -l '$HEIGHT' -nb '$NB' -nf '$NF' -sb '$SB' -sf '$SF' -p '$PROMPT' "
	fi
	
	CMD=$(eval $ACTION)

done
exit 0
